inherit_gem:
  rubocop-rootstrap:
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/*
    - bin/bundle
    - bin/yarn

# Layout/EndOfLine:
#   EnforcedStyle: crlf

Metrics/BlockLength:
  Exclude:
    - '**/**/*.rake'
