inherit_gem:
  rubocop-rootstrap:
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/*
    - bin/bundle
    - bin/yarn

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/api/v1/registrations_controller.rb

Metrics/BlockLength:
  Exclude:
    - '**/**/*.rake'
