
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin1
  password: admin1
  host: localhost
  port: 5432

development:
 <<: *default
 database: targetmvd_development

test:
 <<: *default
 database: targetmvd_test

production:
  adapter: postgresql
  encoding: unicode
  database: targetmvd_production
  pool: 5
  
