env:
  RAILS_ENV: test
  RUBY_VERSION: 3.0.2

name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.2'

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp .github/database.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Formatting and Security Checks
        run: |
          bundle exec rubocop
          bundle exec brakeman 

      - name: Check for missing annotations
        run: bundle exec annotate

      - name: Run RSpec tests
        run: COVERAGE=true bundle exec rspec  --require rails_helper
